version: '3.8'

services:
  rasa:
    image: rasa/rasa:3.4.0
    container_name: rasa_server
    ports:
      - "5005:5005"
    volumes:
      - ./data:/app/data
      - ./models:/app/models
      - ./config.yml:/app/config.yml
      - ./domain.yml:/app/domain.yml
      - ./endpoints.yml:/app/endpoints.yml
      - ./actions:/app/actions
    command: >
      run
      --model /app/models
      --enable-api
      --cors "*"
      --debug
    depends_on:
      - rasa_action

  rasa_action:
    image: rasa/rasa-sdk:3.4.0
    container_name: rasa_action_server
    ports:
      - "5055:5055"
    volumes:
      - ./actions:/app/actions
    command: >
      run
      --actions actions
      --debug

  streamlit:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: streamlit_app
    ports:
      - "8501:8501"
    environment:
      - RASA_SERVER=http://rasa:5005/webhooks/rest/webhook
    depends_on:
      - rasa
      - rasa_action

  duckling:
    image: rasa/duckling
    container_name: duckling
    ports:
      - "8000:8000"
    command: ["duckling-example"]
    restart: unless-stopped
