name: Create Diagram

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  generate_repo_visual:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Generate repository diagram
        uses: githubocto/repo-visualizer@main
        with:
          excluded_paths: ".github"
          output_file: "docs/img/repo_diagram.svg"
